FROM mcr.microsoft.com/devcontainers/base:bullseye
RUN sudo apt-get update 
# RUN sudo apt-get install python3-distutils
RUN sudo apt-get install -y python3-pip
RUN sudo apt-get install -y freecad
# RUN curl -sSL https://install.python-poetry.org | python3 -